//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppWPF.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemCharac { get; set; }
        public string ItemType { get; set; }
    }
}
