//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentPowerPlant
    {
        public int ComponentID { get; set; }
        public string ComponentName { get; set; }
        public string Power { get; set; }
        public string Pressure { get; set; }
        public string Speed { get; set; }
        public string Temparature { get; set; }
    }
}
